package WebService::Beeminder::Types;
use 5.010;
use strict;
use warnings;

# ABSTRACT: Types for WebService::Beeminder
# VERSION: Generated by DZP::OurPkg:Version

use MooseX::Types -declare => [
    qw(
        BeeBool
    )
];

use MooseX::Types::Moose qw(Str Bool);

subtype BeeBool,
    as Str,
    where { /^(?:true|false)$/ }
;

coerce BeeBool,
    from Bool,
    via { $_ ? "true" : "false" }
;

coerce Bool,
    from BeeBool,
    via { $_ eq "true" }
;
