package WebService::Beeminder::Types;
use 5.010;
use strict;
use warnings;

# ABSTRACT: Types for WebService::Beeminder
# VERSION: Generated by DZP::OurPkg:Version

use MooseX::Types -declare => [
    qw(
        BeeBool
        Goal
        User
    )
];

use MooseX::Types::Moose qw(Str Bool);

subtype BeeBool,
    as Str,
    where { /^(?:true|false)$/ }
;

coerce BeeBool,
    from Bool,
    via { $_ ? "true" : "false" }
;

coerce Bool,
    from BeeBool,
    via { $_ eq "true" }
;

# Goal and User types are just strings, but we can tweak them later
# if there are restrictions as to what's a valid user or goal name.

subtype Goal,
    as Str
;

subtype User,
    as Str
;

1;
